import io
import csv
from typing import List, Dict, Optional, Tuple
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

import cloudinary_service
import database

COLUMNS = [
    ("name", "Business Name"),
    ("phone", "Mobile Number"),
    ("whatsapp", "WhatsApp Number"),
    ("email", "Email ID"),
    ("website", "Website"),
    ("address", "Address"),
    ("rating", "Star Rating"),
    ("reviews_count", "Reviews Count"),
    ("niche", "Niche / Category"),
    ("map_url", "Google Maps URL")
]

def export_to_csv(leads: List[Dict]) -> io.BytesIO:
    output = io.StringIO()
    writer = csv.writer(output)
    
    headers = [col[1] for col in COLUMNS]
    writer.writerow(headers)
    
    for lead in leads:
        row = []
        for key, _ in COLUMNS:
            val = lead.get(key, "")
            if val is None:
                val = ""
            row.append(str(val))
        writer.writerow(row)
        
    bytes_io = io.BytesIO()
    bytes_io.write(output.getvalue().encode('utf-8-sig'))
    bytes_io.seek(0)
    return bytes_io

def export_to_excel(leads: List[Dict], title: str = "Extracted Leads") -> io.BytesIO:
    wb = Workbook()
    ws = wb.active
    ws.title = "Leads"

    header_fill = PatternFill(start_color="1E3A8A", end_color="1E3A8A", fill_type="solid")
    header_font = Font(name="Arial", size=11, bold=True, color="FFFFFF")
    data_font = Font(name="Arial", size=10)
    alt_fill = PatternFill(start_color="F1F5F9", end_color="F1F5F9", fill_type="solid")
    
    thin_border = Border(
        left=Side(style='thin', color='CBD5E1'),
        right=Side(style='thin', color='CBD5E1'),
        top=Side(style='thin', color='CBD5E1'),
        bottom=Side(style='thin', color='CBD5E1')
    )

    headers = [col[1] for col in COLUMNS]
    ws.append(headers)

    for cell in ws[1]:
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = thin_border
    ws.row_dimensions[1].height = 28

    for r_idx, lead in enumerate(leads, start=2):
        row_vals = []
        for key, _ in COLUMNS:
            val = lead.get(key, "")
            if val is None:
                val = ""
            row_vals.append(val)
        ws.append(row_vals)
        
        row_cells = ws[r_idx]
        is_even = (r_idx % 2 == 0)
        for cell in row_cells:
            cell.font = data_font
            cell.border = thin_border
            cell.alignment = Alignment(vertical="center")
            if is_even:
                cell.fill = alt_fill
        ws.row_dimensions[r_idx].height = 22

    col_widths = {
        'A': 30, 'B': 18, 'C': 18, 'D': 25, 'E': 25,
        'F': 38, 'G': 12, 'H': 14, 'I': 22, 'J': 30
    }
    for col_letter, width in col_widths.items():
        ws.column_dimensions[col_letter].width = width

    bytes_io = io.BytesIO()
    wb.save(bytes_io)
    bytes_io.seek(0)
    return bytes_io

def export_to_pdf(leads: List[Dict], title: str = "Google Maps Extracted Leads") -> io.BytesIO:
    bytes_io = io.BytesIO()
    doc = SimpleDocTemplate(
        bytes_io,
        pagesize=landscape(letter),
        rightMargin=20,
        leftMargin=20,
        topMargin=25,
        bottomMargin=25
    )

    elements = []
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'MainTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        textColor=colors.HexColor('#1E3A8A'),
        spaceAfter=6
    )
    elements.append(Paragraph(title, title_style))

    sub_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        textColor=colors.HexColor('#475569'),
        spaceAfter=15
    )
    elements.append(Paragraph(f"Total Leads: <b>{len(leads)}</b> | Generated by Google Maps Data Extractor Pro", sub_style))

    cell_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=10,
        textColor=colors.HexColor('#1E293B')
    )
    
    header_style = ParagraphStyle(
        'TableHead',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=11,
        textColor=colors.white
    )

    pdf_cols = [
        ("name", "Name", 120),
        ("phone", "Mobile", 80),
        ("whatsapp", "WhatsApp", 80),
        ("email", "Email", 110),
        ("rating", "Rating", 45),
        ("website", "Website", 110),
        ("address", "Address", 185)
    ]

    table_data = []
    table_data.append([Paragraph(f"<b>{col[1]}</b>", header_style) for col in pdf_cols])

    for lead in leads:
        row = []
        for key, _, _ in pdf_cols:
            val = lead.get(key, "") or "-"
            if key == "rating":
                rc = lead.get("reviews_count", 0)
                val = f"{val} ★ ({rc})" if val != "-" else "-"
            text_val = str(val)[:120]
            row.append(Paragraph(text_val, cell_style))
        table_data.append(row)

    col_widths = [col[2] for col in pdf_cols]
    pdf_table = Table(table_data, colWidths=col_widths, repeatRows=1)
    
    pdf_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')])
    ]))

    elements.append(pdf_table)
    doc.build(elements)
    bytes_io.seek(0)
    return bytes_io

def export_and_upload_pdf(leads: List[Dict], session_id: Optional[str] = None, title: str = "Google Maps Extracted Leads") -> Tuple[io.BytesIO, Optional[str]]:
    """
    Generates the PDF and uploads it to Cloudinary if configured.
    Returns (pdf_bytes_io, cloudinary_url)
    """
    pdf_bytes_io = export_to_pdf(leads, title=title)
    
    cloudinary_url = None
    if cloudinary_service.is_cloudinary_configured():
        filename = f"leads_{session_id or 'export'}.pdf"
        cloudinary_url = cloudinary_service.upload_pdf_to_cloudinary(pdf_bytes_io, filename)
        if cloudinary_url and session_id:
            try:
                database.update_session_pdf_url(session_id, cloudinary_url)
            except Exception as e:
                print(f"[Save Cloudinary URL Error]: {e}")
        pdf_bytes_io.seek(0)
        
    return pdf_bytes_io, cloudinary_url
